language: c

os: linux
addons:
  apt:
    packages:
      - meson
      - nasm
      - ninja-build
      - rustup
before_build:
  - rustup toolchain install stable

matrix:
  include:
  - name: "GCC Debug"
    compiler: gcc
    script:
      - ./scripts/build.sh -DCMAKE_BUILD_TYPE=Debug

  - name: "GCC Release"
    compiler: gcc
    script:
      - ./scripts/build.sh -DCMAKE_BUILD_TYPE=Release

  - name: "Clang Debug"
    compiler: clang
    script:
      - ./scripts/build.sh -DCMAKE_BUILD_TYPE=Debug

  - name: "Clang Release"
    compiler: clang
    script:
      - ./scripts/build.sh -DCMAKE_BUILD_TYPE=Release

  - name: "Clang Test IO"
    compiler: clang
    script:
      - ./scripts/build.sh -DCMAKE_BUILD_TYPE=Release -DCOLORIST_TEST_IO=1
      - ninja -v colorist-test-io
